apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv

spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
    type: DirectoryOrCreate