apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
 
spec:
  storageClassName: "standard" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
    storage: 1Gi