kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo-app
 
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      
      labels:
        app: mongo-app
    spec:
      containers:
       
        - name: mongodb
          image: mongo:latest  
          volumeMounts:
           - mountPath: /data/db
             name: mongo-vol
      volumes:
       - name: mongo-vol
         persistentVolumeClaim:
          claimName: host-pvc     
  

--- 
kind: Service
apiVersion: v1
metadata:
  name: mongodb
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-app
  
  